//=========================================================
// inc/InitDevice.h: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!!
//=========================================================
#ifndef __INIT_DEVICE_H__
#define __INIT_DEVICE_H__

// USER CONSTANTS
#define AU1		0x00
#define AU2		0x01
#define AKU		0x02
#define ARE		0x03

sbit A0 = P2 ^ 4;
sbit A1 = P2 ^ 3;
sbit A2 = P2 ^ 2;

sbit D0 = P2 ^ 1;
sbit D1 = P2 ^ 0;
sbit D2 = P1 ^ 7;
sbit D3 = P1 ^ 6;
sbit D4 = P1 ^ 5;
sbit D5 = P1 ^ 4;
sbit D6 = P1 ^ 3;
sbit D7 = P1 ^ 2;
sbit D8 = P1 ^ 1;
sbit D9 = P1 ^ 0;
sbit D10 = P0 ^ 7;
sbit D11 = P0 ^ 6;
sbit D12 = P0 ^ 5;
sbit D13 = P0 ^ 4;

sbit WR = P3 ^ 1;

sbit DE = P3 ^ 0;

sbit ZERO = P3 ^ 3;
// USER PROTOTYPES

// $[Mode Transition Prototypes]
extern void enter_DefaultMode_from_RESET(void);
// [Mode Transition Prototypes]$

// $[Config(Per-Module Mode)Transition Prototypes]
extern void WDT_0_enter_DefaultMode_from_RESET(void);
extern void PORTS_0_enter_DefaultMode_from_RESET(void);
extern void PORTS_1_enter_DefaultMode_from_RESET(void);
extern void PORTS_2_enter_DefaultMode_from_RESET(void);
extern void PORTS_3_enter_DefaultMode_from_RESET(void);
extern void PBCFG_0_enter_DefaultMode_from_RESET(void);
extern void EXTOSC_0_enter_DefaultMode_from_RESET(void);
extern void CIP51_0_enter_DefaultMode_from_RESET(void);
extern void CLOCK_0_enter_DefaultMode_from_RESET(void);
extern void UARTE_1_enter_DefaultMode_from_RESET(void);
// [Config(Per-Module Mode)Transition Prototypes]$

#endif

